# Generated by Django 4.2.15 on 2024-08-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=80, verbose_name='Nome Cliente')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('servico', models.CharField(max_length=15, null=True, verbose_name='Serviço')),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now=True, verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
