# Generated by Django 4.2.15 on 2024-08-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orcamento_formatted_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='formatted_id',
        ),
    ]
